# Generated by Django 4.0.5 on 2022-07-27 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_options_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['name', '-created']},
        ),
    ]
